language: node_js
node_js: 8
jobs:
  include:
    - stage: lint
      script:
        - yarn run lint:js
        - yarn run lint:spec
    - stage: test
      script:
        - yarn run test
        - yarn run test:mutate
    - stage: build
      script:
        - yarn run build
